// <auto-generated />
using GERENC_INFRAESTRUTURA.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GERENC_INFRAESTRUTURA.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260112003636_inicialcls")]
    partial class inicialcls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GERENC_DOMAIN.Entities.CategoriaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("GERENC_DOMAIN.Entities.PessoaCategoria", b =>
                {
                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.HasKey("PessoaId", "CategoriaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("PessoaCategoria");
                });

            modelBuilder.Entity("GERENC_DOMAIN.Entities.Pessoas.PessoaBaseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoPessoa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pessoa");

                    b.HasDiscriminator().HasValue("PessoaBaseModel");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GERENC_DOMAIN.Entities.Pessoas.AgenteModel", b =>
                {
                    b.HasBaseType("GERENC_DOMAIN.Entities.Pessoas.PessoaBaseModel");

                    b.HasDiscriminator().HasValue("AgenteModel");
                });

            modelBuilder.Entity("GERENC_DOMAIN.Entities.Pessoas.FuncionarioModel", b =>
                {
                    b.HasBaseType("GERENC_DOMAIN.Entities.Pessoas.PessoaBaseModel");

                    b.HasDiscriminator().HasValue("FuncionarioModel");
                });

            modelBuilder.Entity("GERENC_DOMAIN.Entities.Pessoas.InstrutorModel", b =>
                {
                    b.HasBaseType("GERENC_DOMAIN.Entities.Pessoas.PessoaBaseModel");

                    b.HasDiscriminator().HasValue("InstrutorModel");
                });

            modelBuilder.Entity("GERENC_DOMAIN.Entities.Pessoas.PorteiroModel", b =>
                {
                    b.HasBaseType("GERENC_DOMAIN.Entities.Pessoas.PessoaBaseModel");

                    b.HasDiscriminator().HasValue("PorteiroModel");
                });

            modelBuilder.Entity("GERENC_DOMAIN.Entities.PessoaCategoria", b =>
                {
                    b.HasOne("GERENC_DOMAIN.Entities.CategoriaModel", "Categoria")
                        .WithMany("PessoaCategorias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GERENC_DOMAIN.Entities.Pessoas.PessoaBaseModel", "Pessoa")
                        .WithMany("PessoaCategorias")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("GERENC_DOMAIN.Entities.CategoriaModel", b =>
                {
                    b.Navigation("PessoaCategorias");
                });

            modelBuilder.Entity("GERENC_DOMAIN.Entities.Pessoas.PessoaBaseModel", b =>
                {
                    b.Navigation("PessoaCategorias");
                });
#pragma warning restore 612, 618
        }
    }
}
