// <auto-generated />
using GERENC_INFRAESTRUTURA.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GERENC_INFRAESTRUTURA.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260128021118_cursoInit")]
    partial class cursoInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GERENC_DOMAIN.Entities.CategoriaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("GERENC_DOMAIN.Entities.Curso.CursoCategoria", b =>
                {
                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.HasKey("CursoId", "CategoriaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("CursoCategoria");
                });

            modelBuilder.Entity("GERENC_DOMAIN.Entities.Curso.CursoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("GERENC_DOMAIN.Entities.PessoaCategoria", b =>
                {
                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.HasKey("PessoaId", "CategoriaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("PessoaCategoria");
                });

            modelBuilder.Entity("GERENC_DOMAIN.Entities.Pessoas.Adm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("GERENC_DOMAIN.Entities.Pessoas.AgenteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Agentes");
                });

            modelBuilder.Entity("GERENC_DOMAIN.Entities.Pessoas.PessoaBaseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoPessoa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pessoas");

                    b.HasDiscriminator().HasValue("PessoaBaseModel");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GERENC_DOMAIN.Entities.Pessoas.PorteiroModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Porteiros");
                });

            modelBuilder.Entity("GERENC_DOMAIN.Entities.Sala.ChaveModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SalaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SalaId");

                    b.ToTable("Chaves");
                });

            modelBuilder.Entity("GERENC_DOMAIN.Entities.Sala.SalaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Salas");
                });

            modelBuilder.Entity("GERENC_DOMAIN.Entities.Usuario.UsuarioBaseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Usuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GERENC_DOMAIN.Entities.Pessoas.FuncionarioModel", b =>
                {
                    b.HasBaseType("GERENC_DOMAIN.Entities.Pessoas.PessoaBaseModel");

                    b.HasDiscriminator().HasValue("FuncionarioModel");
                });

            modelBuilder.Entity("GERENC_DOMAIN.Entities.Pessoas.InstrutorModel", b =>
                {
                    b.HasBaseType("GERENC_DOMAIN.Entities.Pessoas.PessoaBaseModel");

                    b.HasDiscriminator().HasValue("InstrutorModel");
                });

            modelBuilder.Entity("GERENC_DOMAIN.Entities.Curso.CursoCategoria", b =>
                {
                    b.HasOne("GERENC_DOMAIN.Entities.CategoriaModel", "Categoria")
                        .WithMany("CursoCategorias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GERENC_DOMAIN.Entities.Curso.CursoModel", "Curso")
                        .WithMany("CursoCategorias")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("GERENC_DOMAIN.Entities.PessoaCategoria", b =>
                {
                    b.HasOne("GERENC_DOMAIN.Entities.CategoriaModel", "Categoria")
                        .WithMany("PessoaCategorias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GERENC_DOMAIN.Entities.Pessoas.PessoaBaseModel", "Pessoa")
                        .WithMany("PessoaCategorias")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("GERENC_DOMAIN.Entities.Pessoas.Adm", b =>
                {
                    b.HasOne("GERENC_DOMAIN.Entities.Pessoas.PessoaBaseModel", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GERENC_DOMAIN.Entities.Usuario.UsuarioBaseModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GERENC_DOMAIN.Entities.Pessoas.AgenteModel", b =>
                {
                    b.HasOne("GERENC_DOMAIN.Entities.Pessoas.PessoaBaseModel", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GERENC_DOMAIN.Entities.Usuario.UsuarioBaseModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GERENC_DOMAIN.Entities.Pessoas.PorteiroModel", b =>
                {
                    b.HasOne("GERENC_DOMAIN.Entities.Pessoas.PessoaBaseModel", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GERENC_DOMAIN.Entities.Usuario.UsuarioBaseModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GERENC_DOMAIN.Entities.Sala.ChaveModel", b =>
                {
                    b.HasOne("GERENC_DOMAIN.Entities.Sala.SalaModel", "sala")
                        .WithMany("Chaves")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("sala");
                });

            modelBuilder.Entity("GERENC_DOMAIN.Entities.CategoriaModel", b =>
                {
                    b.Navigation("CursoCategorias");

                    b.Navigation("PessoaCategorias");
                });

            modelBuilder.Entity("GERENC_DOMAIN.Entities.Curso.CursoModel", b =>
                {
                    b.Navigation("CursoCategorias");
                });

            modelBuilder.Entity("GERENC_DOMAIN.Entities.Pessoas.PessoaBaseModel", b =>
                {
                    b.Navigation("PessoaCategorias");
                });

            modelBuilder.Entity("GERENC_DOMAIN.Entities.Sala.SalaModel", b =>
                {
                    b.Navigation("Chaves");
                });
#pragma warning restore 612, 618
        }
    }
}
